// File generated by Antigravity for Firebase initialization across Web and Android.
import 'package:flutter/foundation.dart'
    show kIsWeb, defaultTargetPlatform, TargetPlatform;
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with `Firebase.initializeApp`.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        return android;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD18OtbEdKTqtD6DM45h7Gm1F0pbgMgfQ',
    appId: '1:161422365876:web:e57feec3c9075ed5b233e1',
    messagingSenderId: '161422365876',
    projectId: 'shelf-chef-app',
    authDomain: 'shelf-chef-app.firebaseapp.com',
    storageBucket: 'shelf-chef-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD18OtbEdKTqtD6DM45h7Gm1F0pbgMgfQ',
    appId: '1:161422365876:android:e57feec3c9075ed5b233e1',
    messagingSenderId: '161422365876',
    projectId: 'shelf-chef-app',
    storageBucket: 'shelf-chef-app.firebasestorage.app',
  );
}
